spring.jpa.hibernate.dll-auto=update
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/pijn
spring.datasource.username=root
spring.datasource.password=root

jwt.key=yl9Dp6VY7Y2x8KuL+90bj7OXN1RDeYdR45yqXQZTcJo=
jwt.expiry=3600000

spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=your-email@example.com
spring.mail.password=your-email-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

cloud.aws.region.static=your_aws_region
cloud.aws.credentials.accessKey=your_access_key
cloud.aws.credentials.secretKey=your_secret_key

cloud.aws.s3.bucket=my-s3-bucket-name